<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>bin\Debug\net9.0-windows\icon1.ico</ApplicationIcon>
    <AssemblyVersion>0.9.0.0</AssemblyVersion>
    <FileVersion>0.9.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="node_logo.png" />
    <None Remove="python_Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net9.0-windows\icon1.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="bin\editorRules.xshd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autoupdater.NET.Official" Version="1.9.2" />
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="LibGit2Sharp.NativeBinaries" Version="2.0.323" />
    <PackageReference Include="Meziantou.Framework.Win32.CredentialManager" Version="2.0.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4022.49" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\External Langauage Manager\External Langauage Manager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="node_logo.png" />
    <Resource Include="python_Logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="version.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>version.txt</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Binaries\Compatible Binaries\" />
    <Folder Include="Binaries\Custom Binaries\" />
    <Folder Include="Binaries\php\" />
    <Folder Include="uninstall\" />
    <Folder Include="Plugins\Custom Plugins\" />
  </ItemGroup>

	<Target Name="DeleteAutoUpdaterLanguages" AfterTargets="AfterBuild">
		<ItemGroup>
			<AutoUpdaterLanguages Include="$(TargetDir)*\AutoUpdater.NET.resources.dll" />
		</ItemGroup>

		<Delete Files="@(AutoUpdaterLanguages)" />

		<RemoveDir Directories="@(AutoUpdaterLanguages->'%(RootDir)%(Directory)')" />
	</Target>
	
</Project>
